spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SERVER_URL}
    username: ${SERVER_USER}
    password: ${SERVER_PASSWORD}
  config:
    import: "aws-secretsmanager:/secrets/esp-secret"
  main.allow-bean-definition-overriding: true

  cloud:
    aws:
      endpoint: ${URL_AWS}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
#        profile: ${AWS_PROFILE}
      region:
        static: ${REGION}
      secretsmanager:
        endpoint: ${URL_AWS}
      s3:
        endpoint: ${URL_AWS}



## Base URL para im\u00e1genes en desarrollo
#especializacion:
#  url:
#    base-imagenes: ${URL_BASE}
#  ruta:
#    #    imagenes: ${VOL_MOUNT_IMAGENES}
#    imagenes: ${BUCKET_IMG}
#    imagenes-vacantes: ${VOL_MOUNT_VACANTES}
#    documentos: ${VOL_MOUNT_DOCUMENTOS}

